name: Build & Release Sayit

on:
  push:
    tags:
      - "v*.*.*"   # e.g. v1.0.0
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    name: Build Sayit Compiler
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install llvmlite

      - name: Build package
        run: |
          mkdir build
          cp -r say_lexer.py say_parser.py say_vm.py say_codegen.py sayc.py build/
          echo "#!/usr/bin/env python3" | cat - build/sayc.py > build/sayc && chmod +x build/sayc

      - name: Package artifacts
        run: |
          cd build
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            powershell Compress-Archive * sayit-${{ matrix.os }}.zip
          else
            tar -czf sayit-${{ matrix.os }}.tar.gz *
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sayit-${{ matrix.os }}
          path: build/*.zip, build/*.tar.gz

  release:
    name: Publish GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
